#! /usr/bin/env bash
set -o nounset
set -o errexit

# directory
export BASE_DIRECTORY="${BASE_DIRECTORY:-.}"
export BASE_DIRECTORY="${BASE_DIRECTORY%/}"

export SRC_DIRECTORY="${BASE_DIRECTORY}/${SRC_DIRECTORY:-src}"
export SRC_DIRECTORY="${SRC_DIRECTORY%/}"

export OUT_DIRECTORY="${BASE_DIRECTORY}/${OUT_DIRECTORY:-out}"
export OUT_DIRECTORY="${OUT_DIRECTORY%/}"

# alias
export ROOT_ALIAS="${ROOT_ALIAS:-root}"
export INTERMEDIATE_ALIAS="${INTERMEDIATE_ALIAS:-intermediate}"
export SUBJECT_ALIAS="${SUBJECT_ALIAS:-subject}"

# keyalg
export KEYALG="${KEY_ALG:-rsa}"
export ROOT_KEYALG="${ROOT_KEYALG:-$KEYALG}"
export INTERMEDIATE_KEYALG="${INTERMEDIATE_KEYALG:-$KEYALG}"
export SUBJECT_KEYALG="${SUBJECT_KEYALG:-$KEYALG}"

# keysize
export KEYSIZE="${KEYSIZE:-4096}"
export ROOT_KEYSIZE="${ROOT_KEYSIZE:-$KEYSIZE}"
export INTERMEDIATE_KEYSIZE="${INTERMEDIATE_KEYSIZE:-$KEYSIZE}"
export SUBJECT_KEYSIZE="${SUBJECT_KEYSIZE:-$KEYSIZE}"

# sigalg
export SIGALG="${SIGALG:-sha512withrsa}"
export ROOT_SIGALG="${ROOT_SIGALG:-$SIGALG}"
export INTERMEDIATE_SIGALG="${INTERMEDIATE_SIGALG:-$SIGALG}"
export SUBJECT_SIGALG="${SUBJECT_SIGALG:-$SIGALG}"

# keypass
export KEYPASS="${KEYPASS:-changeit}"
export ROOT_KEYPASS="${ROOT_KEYPASS:-$KEYPASS}"
export INTERMEDIATE_KEYPASS="${INTERMEDIATE_KEYPASS:-$KEYPASS}"
export SUBJECT_KEYPASS="${SUBJECT_KEYPASS:-$KEYPASS}"

# storepass
export STOREPASS="${STOREPASS:-changeit}"
export ROOT_STOREPASS="${ROOT_STOREPASS:-$STOREPASS}"
export INTERMEDIATE_STOREPASS="${INTERMEDIATE_STOREPASS:-$STOREPASS}"
export SUBJECT_STOREPASS="${SUBJECT_STOREPASS:-$STOREPASS}"

# storetype
export STORETYPE="${STORETYPE:-jks}"
export ROOT_STORETYPE="${ROOT_STORETYPE:-$STORETYPE}"
export INTERMEDIATE_STORETYPE="${INTERMEDIATE_STORETYPE:-$STORETYPE}"
export SUBJECT_STORETYPE="${SUBJECT_STORETYPE:-$STORETYPE}"

# keystore
export ROOT_KEYSTORE="${OUT_DIRECTORY}/${ROOT_KEYSTORE:-$ROOT_ALIAS.$ROOT_STORETYPE}"
export INTERMEDIATE_KEYSTORE="${OUT_DIRECTORY}/${INTERMEDIATE_KEYSTORE:-$INTERMEDIATE_ALIAS.$INTERMEDIATE_STORETYPE}"
export SUBJECT_KEYSTORE="${OUT_DIRECTORY}/${SUBJECT_KEYSTORE:-$SUBJECT_ALIAS.$SUBJECT_STORETYPE}"

# domain
export DOMAIN="${DOMAIN:-lvh.me}"
export ROOT_DOMAIN="${ROOT_DOMAIN:-$ROOT_ALIAS.$DOMAIN}"
export INTERMEDIATE_DOMAIN="${INTERMEDIATE_DOMAIN:-$INTERMEDIATE_ALIAS.$DOMAIN}"
export SUBJECT_DOMAIN="${SUBJECT_DOMAIN:-$SUBJECT_ALIAS.$DOMAIN}"

# dname
export COMMON_NAME=""
export ORGANIZATIONAL_UNIT=""
export ORGANIZATION=""
export LOCALITY="${LOCALITY:-New York City}"
export STATE="${STATE:-New York}"
export COUNTRY="${COUNTRY:-US}"

# dname
export ROOT_COMMON_NAME="${ROOT_COMMON_NAME:-$ROOT_DOMAIN}"
export ROOT_ORGANIZATIONAL_UNIT="${ROOT_ORGANIZATIONAL_UNIT:-$ROOT_ALIAS}"
export ROOT_ORGANIZATION="${ROOT_ORGANIZATION:-$ROOT_ALIAS}"
export ROOT_LOCALITY="${ROOT_LOCALITY:-$LOCALITY}"
export ROOT_STATE="${ROOT_STATE:-$STATE}"
export ROOT_COUNTRY="${ROOT_COUNTRY:-$COUNTRY}"

# dname
export INTERMEDIATE_COMMON_NAME="${INTERMEDIATE_COMMON_NAME:-$INTERMEDIATE_DOMAIN}"
export INTERMEDIATE_ORGANIZATIONAL_UNIT="${INTERMEDIATE_ORGANIZATIONAL_UNIT:-$INTERMEDIATE_ALIAS}"
export INTERMEDIATE_ORGANIZATION="${INTERMEDIATE_ORGANIZATION:-$INTERMEDIATE_ALIAS}"
export INTERMEDIATE_LOCALITY="${INTERMEDIATE_LOCALITY:-$LOCALITY}"
export INTERMEDIATE_STATE="${INTERMEDIATE_STATE:-$STATE}"
export INTERMEDIATE_COUNTRY="${INTERMEDIATE_COUNTRY:-$COUNTRY}"

# dname
export SUBJECT_COMMON_NAME="${SUBJECT_COMMON_NAME:-$SUBJECT_DOMAIN}"
export SUBJECT_ORGANIZATIONAL_UNIT="${SUBJECT_ORGANIZATIONAL_UNIT:-$SUBJECT_ALIAS}"
export SUBJECT_ORGANIZATION="${SUBJECT_ORGANIZATION:-$SUBJECT_ALIAS}"
export SUBJECT_LOCALITY="${SUBJECT_LOCALITY:-$LOCALITY}"
export SUBJECT_STATE="${SUBJECT_STATE:-$STATE}"
export SUBJECT_COUNTRY="${SUBJECT_COUNTRY:-$COUNTRY}"

# csr
export CERTIFICATE_SIGNING_REQUEST_EXTENSION="${CERTIFICATE_SIGNING_REQUEST_EXTENSION:-csr}"

export ROOT_CERTIFICATE_SIGNING_REQUEST="${OUT_DIRECTORY}/${ROOT_CERTIFICATE_SIGNING_REQUEST:-$ROOT_ALIAS.$CERTIFICATE_SIGNING_REQUEST_EXTENSION}"
export INTERMEDIATE_CERTIFICATE_SIGNING_REQUEST="${OUT_DIRECTORY}/${INTERMEDIATE_CERTIFICATE_SIGNING_REQUEST:-$INTERMEDIATE_ALIAS.$CERTIFICATE_SIGNING_REQUEST_EXTENSION}"
export SUBJECT_CERTIFICATE_SIGNING_REQUEST="${OUT_DIRECTORY}/${SUBJECT_CERTIFICATE_SIGNING_REQUEST:-$SUBJECT_ALIAS.$CERTIFICATE_SIGNING_REQUEST_EXTENSION}"

# pem
export CERTIFICATE_EXTENSION="${CERTIFICATE_EXTENSION:-pem}"

export ROOT_CERTIFICATE="${OUT_DIRECTORY}/${ROOT_CERTIFICATE:-$ROOT_ALIAS.$CERTIFICATE_EXTENSION}"
export INTERMEDIATE_CERTIFICATE="${OUT_DIRECTORY}/${INTERMEDIATE_CERTIFICATE:-$INTERMEDIATE_ALIAS.$CERTIFICATE_EXTENSION}"
export SUBJECT_CERTIFICATE="${OUT_DIRECTORY}/${SUBJECT_CERTIFICATE:-$SUBJECT_ALIAS.$CERTIFICATE_EXTENSION}"
